import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {motion} from 'framer-motion';
import {ArrowDown, ArrowUpRight, Check, Mail, Sparkles} from 'lucide-react';
import './styles.css';

const services=[
['01','Digtal Creator','Concept Development · Visual Direction · Storytelling · Campaign Ideas · Content Planning'],
['02','Video Editing & Post-Production','Cinematic Editing · Reels & Shorts · Promotional Videos · Color Grading · Motion Graphics'],
['03','Digital Marketing','Social Media Strategy · Content Marketing · Campaign Planning · Audience Research · Brand Positioning'],
['04','Digital Content Creation','Social Media Creatives · Posters · Promotional Content · Reels · Short-form Content'],
['05','Graphic & Visual Design','Poster Design · Ad Creatives · Thumbnails · Branding Materials · Marketing Designs'],
['06','Freelance Creative Services','Flexible end-to-end creative support — from one social creative to a complete digital campaign.']
];
const skills=['Creative Direction','Video Editing','Digital Marketing','Content Creation','Graphic Design','Social Media Marketing','Visual Storytelling','Brand Development','Content Strategy','Color Grading','Motion Graphics','AI-Assisted Creative Workflow'];
const process=[['01','Discover','Understand the brand, audience and objective.'],['02','Ideate','Develop concepts, references and possibilities.'],['03','Create','Transform the selected concept into visual content.'],['04','Refine','Polish composition, color, type, sound and details.'],['05','Deliver','Optimize and deliver for the required platform.']];
const work=[['Brand & Social Media','Campaigns, promotional posters and visual branding.'],['Video & Cinematic Content','Reels, advertisements and storytelling-driven edits.'],['Digital Marketing','Strategies focused on reach, engagement and awareness.'],['Creative Direction','Concept to final frame — a complete visual direction.']];
const tools=['Photoshop','Premiere Pro','After Effects','Illustrator','CorelDRAW','Canva','CapCut','AI Tools'];
const reveal={initial:{opacity:0,y:45,scale:.98},whileInView:{opacity:1,y:0,scale:1},viewport:{once:true,amount:.25},transition:{duration:.8,ease:[.22,1,.36,1]}};
function App(){
 const [scrolled,setScrolled]=useState(false); const [active,setActive]=useState('home');
 useEffect(()=>{const on=()=>setScrolled(scrollY>30); addEventListener('scroll',on);on(); const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{rootMargin:'-40% 0px -50%'}); document.querySelectorAll('section[id]').forEach(s=>obs.observe(s)); return()=>{removeEventListener('scroll',on);obs.disconnect()};},[]);
 const go=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
 return <main>
  <nav className={scrolled?'nav scrolled':'nav'}><button className="brand" onClick={()=>go('home')}>SHAMEER<span>.</span></button><div className="links">{[['about','About'],['services','Services'],['work','Work']].map(([id,l])=><button className={active===id?'active':''} onClick={()=>go(id)} key={id}>{l}</button>)}</div><button className="navCta" onClick={()=>go('contact')}>Let's talk <ArrowUpRight size={16}/></button></nav>
  <section id="home" className="hero"><div className="heroGlow"/><motion.div className="portraitWrap" initial={{opacity:0,scale:1.08}} animate={{opacity:1,scale:1}} transition={{duration:1.4}}><img src="/portrait.jpg" alt="Shameer portfolio portrait"/></motion.div><motion.div className="heroContent" initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} transition={{delay:.2,duration:1}}><div className="eyebrow"><Sparkles size={15}/> Digital Creator</div><h1>B. Muhammad<br/><span>Shameer</span></h1><p className="roles">Creative Direction. Video Editing. Digital Marketing. Freelancer.</p><p className="tagline">Creating ideas. Crafting visuals. Building digital experiences.</p><button className="primary" onClick={()=>go('work')}>See the Work <ArrowDown size={18}/></button></motion.div></section>
  <section id="about" className="section dark"><motion.div {...reveal} className="narrow"><p className="kicker">About</p><h2>A multidisciplinary creator turning ideas into <span>meaningful visual experiences.</span></h2><p className="lead">My work combines creative direction, video editing, digital marketing, visual storytelling and content creation to help brands, businesses and individuals communicate with clarity and impact.</p><div className="flow">{['Idea','Strategy','Creation','Execution','Delivery'].map((x,i)=><React.Fragment key={x}><b>{x}</b>{i<4&&<span>→</span>}</React.Fragment>)}</div></motion.div></section>
  <section id="services" className="services"><div className="sectionIntro"><p className="kicker">What I Do</p><h2>One creator.<br/>Multiple disciplines.</h2></div>{services.map((s,i)=><section className={'service '+(i%2?'dark':'light')} key={s[0]}><motion.div {...reveal} className="serviceInner"><div className="num">{s[0]}</div><h3>{s[1]}</h3><p>{s[2]}</p></motion.div></section>)}</section>
  <section className="section skills"><motion.div {...reveal}><p className="kicker">Creative Skills</p><h2>Built for modern creative work.</h2><div className="tags">{skills.map(x=><span key={x}>{x}</span>)}</div></motion.div></section>
  <section className="section dark"><motion.div {...reveal}><p className="kicker">My Process</p><h2>From first thought to final frame.</h2><div className="process">{process.map(p=><div className="processCard" key={p[0]}><b>{p[0]}</b><h3>{p[1]}</h3><p>{p[2]}</p></div>)}</div></motion.div></section>
  <section id="work" className="section work"><motion.div {...reveal}><p className="kicker">Selected Work</p><h2>Ideas, made visible.</h2></motion.div><div className="workList">{work.map((w,i)=><motion.article {...reveal} className="workCard" key={w[0]}><div className="workVisual"><div className="orb">0{i+1}</div><span>{w[0]}</span></div><h3>{w[0]}</h3><p>{w[1]}</p></motion.article>)}</div></section>
  <section className="section dark"><motion.div {...reveal}><p className="kicker">Why Work With Me</p><h2>Creativity + strategy + technology.</h2><div className="features">{['Strong Concepts','Premium Visual Quality','Purposeful Content','Modern Creative Workflow','End-to-End Execution'].map(x=><div key={x}><Check/><span>{x}</span></div>)}</div><div className="tools"><small>TOOLS & CREATIVE WORKFLOW</small><div>{tools.map(x=><span key={x}>{x}</span>)}</div></div></motion.div></section>
  <section className="quote"><motion.blockquote {...reveal}>"I don't just create content.<br/><em>I transform ideas into digital experiences.</em>"</motion.blockquote></section>
  <section id="contact" className="contact"><motion.div {...reveal}><p className="kicker">Available for new projects</p><h2>Let's Create<br/>Something Great.</h2><p>Have an idea, brand or project? Let's turn it into something people remember.</p><a className="primary" href="mailto:shameer2001smr@gmail.com"><Mail size={18}/> Start a Conversation</a><div className="contactInfo"><a href="mailto:shameer2001smr@gmail.com">shameer2001smr@gmail.com</a><a href="tel:+916383458200">+91 63834 58200</a></div><div className="availability">{['Freelance Projects','Brand Collaborations','Creative Direction','Video Editing','Digital Marketing'].map(x=><span key={x}>{x}</span>)}</div><footer><b>B. Muhammad Shameer</b><span>Digital Creator · Creative Director · Video Editor · Freelancer</span><small>© 2026 Shameer. Crafted with purpose.</small></footer></motion.div></section>
 </main> 
 <img src="/work1.jpg" alt="My work" style={{width:'100%',borderRadius:'20px'}}/>
}
createRoot(document.getElementById('root')).render(<App/>);
